2020-01-21 05:55:11.280483: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 05:55:11.280611: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 05:55:11.280628: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 05:55:20.575932: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-21 05:55:20.580961: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-01-21 05:55:20.580993: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node032): /proc/driver/nvidia/version does not exist
2020-01-21 05:55:20.590431: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2800135000 Hz
2020-01-21 05:55:20.591437: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555bf34c70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 05:55:20.591460: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 05:55:25.469340: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 05:55:25.476130: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 05:55:25.476191: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 05:55:25.476234: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 05:55:25.488221: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 05:55:25.488284: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 07:34:13.938849: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 07:34:13.938927: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 07:34:13.938939: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 07:34:13.949194: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 07:34:13.949237: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 09:15:31.832298: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 09:15:31.832438: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 09:15:31.832464: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 09:15:31.845546: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 09:15:31.845584: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
/cm/shared/apps/anaconda/anaconda3/5.0.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2020-01-21 10:26:05.351315: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 10:26:05.351437: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 10:26:05.351453: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 10:26:13.660701: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-21 10:26:13.664973: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-01-21 10:26:13.665006: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node032): /proc/driver/nvidia/version does not exist
2020-01-21 10:26:13.674212: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2800135000 Hz
2020-01-21 10:26:13.675142: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555bf34bb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 10:26:13.675165: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 10:26:15.843875: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 10:26:15.848093: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 10:26:15.848126: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 10:26:15.848142: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 10:26:15.857609: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 10:26:15.857639: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 11:20:20.042826: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 11:20:20.042977: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 11:20:20.043007: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 11:20:20.052807: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 11:20:20.052866: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 12:07:01.853655: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 12:07:01.853751: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 12:07:01.853766: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 12:07:01.863839: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 12:07:01.863868: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
/cm/shared/apps/anaconda/anaconda3/5.0.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2020-01-21 12:50:23.128343: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 12:50:23.128460: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 12:50:23.128475: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 12:50:31.377976: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-21 12:50:31.381931: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-01-21 12:50:31.381963: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node032): /proc/driver/nvidia/version does not exist
2020-01-21 12:50:31.391309: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2800135000 Hz
2020-01-21 12:50:31.392233: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555bf35840 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 12:50:31.392256: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 12:50:34.335166: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 12:50:34.341592: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 12:50:34.341656: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 12:50:34.341684: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 12:50:34.354143: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 12:50:34.354185: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 14:14:11.904571: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 14:14:11.904703: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 14:14:11.904731: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 14:14:11.915009: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 14:14:11.915039: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 15:23:48.003269: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 15:23:48.003354: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 15:23:48.003367: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 15:23:48.011888: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 15:23:48.011918: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
/cm/shared/apps/anaconda/anaconda3/5.0.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2020-01-21 16:52:58.497428: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 16:52:58.497591: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 16:52:58.497614: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-01-21 16:53:06.619076: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-01-21 16:53:06.623045: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2020-01-21 16:53:06.623077: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node032): /proc/driver/nvidia/version does not exist
2020-01-21 16:53:06.632510: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2800135000 Hz
2020-01-21 16:53:06.633479: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55555bf343a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-21 16:53:06.633501: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-01-21 16:53:08.765867: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 16:53:08.772678: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcupti.so.10.1'; dlerror: libcupti.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /cm/shared/apps/slurm/15.08.13/lib64/slurm:/cm/shared/apps/slurm/15.08.13/lib64:/cm/local/apps/gcc/5.2.0/lib:/cm/local/apps/gcc/5.2.0/lib64:/cm/local/apps/cuda-driver/libs/390.46/lib64/
2020-01-21 16:53:08.772740: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 16:53:08.772776: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 16:53:08.784461: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 16:53:08.784515: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 17:31:44.775593: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 17:31:44.775778: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 17:31:44.775808: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 17:31:44.786793: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 17:31:44.786841: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
2020-01-21 18:11:41.586964: I tensorflow/core/profiler/lib/profiler_session.cc:225] Profiler session started.
2020-01-21 18:11:41.587095: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1307] function cupti_interface_->Subscribe( &subscriber_, (CUpti_CallbackFunc)ApiCallback, this)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 18:11:41.587123: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1346] function cupti_interface_->ActivityRegisterCallbacks( AllocCuptiActivityBuffer, FreeCuptiActivityBuffer)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 18:11:41.596754: E tensorflow/core/profiler/internal/gpu/cupti_tracer.cc:1329] function cupti_interface_->EnableCallback( 0 , subscriber_, CUPTI_CB_DOMAIN_DRIVER_API, cbid)failed with error CUPTI could not be loaded or symbol could not be found.
2020-01-21 18:11:41.596806: I tensorflow/core/profiler/internal/gpu/device_tracer.cc:88]  GpuTracer has collected 0 callback api events and 0 activity events.
/cm/shared/apps/anaconda/anaconda3/5.0.1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
